Repository jailmanager/jailman, pull requests merged in 2020-06, with the labels that each got.

#162 Traefik dynamic config generator
  blueprints/bazarr/config.yml
  blueprints/bazarr/install.sh
  blueprints/bitwarden/config.yml
  blueprints/bitwarden/install.sh
  blueprints/forked_daapd/config.yml
  blueprints/forked_daapd/install.sh
  blueprints/grafana/config.yml
  blueprints/grafana/install.sh
  blueprints/jackett/config.yml
  blueprints/jackett/install.sh
  blueprints/lidarr/config.yml
  blueprints/lidarr/install.sh
  blueprints/mariadb/config.yml
  blueprints/mariadb/install.sh
  blueprints/nextcloud/config.yml
  blueprints/nextcloud/install.sh
  blueprints/organizr/config.yml
  blueprints/organizr/install.sh
  blueprints/plex/config.yml
  blueprints/plex/install.sh
  blueprints/radarr/config.yml
  blueprints/radarr/install.sh
  blueprints/sabnzbd/config.yml
  blueprints/sabnzbd/install.sh
  blueprints/sonarr/config.yml
  blueprints/sonarr/install.sh
  blueprints/tautulli/config.yml
  blueprints/tautulli/install.sh
  blueprints/traefik/includes/buildin_middlewares.toml
  blueprints/traefik/includes/dashboard.toml
  blueprints/traefik/includes/dashboard_wildcard.toml
  blueprints/traefik/includes/default.toml
  blueprints/traefik/includes/default_auth_basic.toml
  blueprints/traefik/includes/default_auth_forward.toml
  blueprints/traefik/install.sh
  blueprints/transmission/config.yml
  blueprints/transmission/install.sh
  blueprints/unifi/config.yml
  blueprints/unifi/install.sh
  includes/global.sh
  includes/global.yml
  jailman.sh
Labels: Feature, enhancement

#156 Plex rework
  blueprints/plex/config.yml
  blueprints/plex/includes/hw_transcoding.sh
  blueprints/plex/install.sh
  blueprints/plex/readme.md
  docs/CODEOWNERS
Labels: enhancement

#161 Auto-connect grafana to unifi-poller data
  blueprints/grafana/config.yml
  blueprints/grafana/install.sh
  blueprints/grafana/readme.md
  config.yml.example
Labels: Feature, enhancement

#165 Stricter bash options.
  .github/workflows/shellcheck.yml
  blueprints/sabnzbd3/install.sh
  blueprints/traefik/includes/buildin_middlewares.toml
  blueprints/traefik/includes/dashboard.toml
  blueprints/traefik/includes/dashboard_wildcard.toml
  blueprints/traefik/includes/default.toml
  includes/blueprint_functions.sh
  includes/global.sh
  includes/global_functions.sh
  includes/init_functions.sh
  includes/libstrict.sh
  jailman.sh
Labels: bug, enhancement
