Repository jailmanager/jailman, pull requests merged in 2020-04, with the labels that each got.

#60 Add right packages to example config for *arr
  config.yml.example
Labels: bug

#59 Add restart warning after update
  global.sh
Labels: enhancement

#58 Add central ports mount for all jails
  global.sh
  jails/nextcloud/install.sh
Labels: enhancement

#57 Changed jail creation to always create base jails
  global.sh
  jails/jackett/install.sh
  jails/lidarr/install.sh
  jails/radarr/install.sh
  jails/sonarr/install.sh
Labels: enhancement

#61 Jail-Specific config.yml
  .gitignore
  config.yml.example
  jailman.sh
  jails/bitwarden/config.yml
  jails/influxdb/config.yml
  jails/jackett/config.yml
  jails/kms/config.yml
  jails/lidarr/config.yml
  jails/mariadb/config.yml
  jails/nextcloud/config.yml
  jails/organizr/config.yml
  jails/plex/config.yml
  jails/radarr/config.yml
  jails/sonarr/config.yml
  jails/tautulli/config.yml
  jails/transmission/config.yml
Labels: enhancement, help wanted

#76 Add documentation for config options
  docs/config options.md
Labels: documentation

#81 Update nextcloud
  jails/nextcloud/config.yml
  jails/nextcloud/install.sh
Labels: enhancement

#77 Rename plexpass to beta and document the beta flag
  config.yml.example
  jails/plex/install.sh
  jails/plex/readme.md
  jails/plex/update.sh
Labels: documentation, enhancement

#78 add plex user to video group
  jails/plex/install.sh
Labels: enhancement

#80 Automatically detect mountpoint for iocage
  config.yml.example
  jailman.sh
Labels: enhancement

#79 Add plex transcoding ramdisk creation
  jails/plex/install.sh
  jails/plex/readme.md
Labels: Feature, enhancement

#86 Wiki replacement and CI update
  .github/workflows/filecheck.yml
  .github/workflows/shellcheck.yml
  .github/workflows/wiki.yml
  LICENSE
  docs/CONTRIBUTING.md
  docs/ISSUE_TEMPLATE.md
  docs/PULL_REQUEST_TEMPLATE.md
  docs/Readme.md
  docs/config options.md
  docs/index.md
  docs/jails/jails.md
  docs/test.md
  jails/bitwarden/readme.md
  jails/influxdb/readme.md
  jails/kms/readme.md
  jails/lidarr/readme.md
  jails/mariadb/readme.md
  jails/nextcloud/readme.md
  jails/organizr/readme.md
  jails/radarr/readme.md
  jails/sonarr/readme.md
  jails/tautulli/readme.md
  jails/transmission/readme.md
  mkdocs.yml
  wiki/Home.md
  wiki/test.md
Labels: Feature, documentation, enhancement

#87 Fixes for recent changes
  config.yml.example
  global.sh
  jailman.sh
Labels: bug

#75 Add Unifi Controller with integrated Unifi-Poller
  config.yml.example
  docs/Readme.md
  jails/unifi/config.yml
  jails/unifi/includes/mongodb.conf
  jails/unifi/includes/rc/mongod
  jails/unifi/includes/rc/unifi
  jails/unifi/includes/rc/unifi_poller
  jails/unifi/includes/up.conf
  jails/unifi/install.sh
  jails/unifi/readme.md
  jails/unifi/update.sh
Labels: Feature
