Repository jailmanager/jailman, pull requests merged in 2020-05, with the labels that each got.

#118 Emergency master fix due to move
  .cirrus.yml
  docs/Readme.md
  global.sh
  jailman.sh
Labels: bug

#119 devnull all the things, we do our own messages
  global.sh
Labels: bug

#123 add code owners
  docs/CODEOWNERS
Labels: enhancement

#133 Make auto-update git aware
  global.sh
  jailman.sh
Labels: enhancement

#135 Make sure mariadb could save persistant
  blueprints/mariadb/install.sh
Labels: bug

#130 Update all the things/blueprints
  blueprints/bitwarden/config.yml
  blueprints/jackett/install.sh
  blueprints/lidarr/install.sh
  blueprints/mariadb/config.yml
  blueprints/nextcloud/config.yml
  blueprints/nextcloud/install.sh
  blueprints/organizr/config.yml
  blueprints/transmission/update.sh
Labels: enhancement

#136 exit on dataset creation/mount errors
  global.sh
Labels: bug

#137 Don't try to update unifi poller if it isn't installed
  blueprints/unifi/update.sh
Labels: bug

#120 Blueprint Init refactor
  blueprints/bitwarden/config.yml
  blueprints/bitwarden/install.sh
  blueprints/bitwarden/readme.md
  blueprints/bitwarden/update.sh
  blueprints/example/config.yml
  blueprints/example/install.sh
  blueprints/example/readme.md
  blueprints/example/update.sh
  blueprints/influxdb/config.yml
  blueprints/influxdb/install.sh
  blueprints/influxdb/update.sh
  blueprints/jackett/install.sh
  blueprints/jackett/update.sh
  blueprints/kms/install.sh
  blueprints/kms/update.sh
  blueprints/lidarr/install.sh
  blueprints/lidarr/update.sh
  blueprints/mariadb/config.yml
  blueprints/mariadb/install.sh
  blueprints/mariadb/readme.md
  blueprints/mariadb/update.sh
  blueprints/nextcloud/config.yml
  blueprints/nextcloud/install.sh
  blueprints/nextcloud/readme.md
  blueprints/nextcloud/update.sh
  blueprints/organizr/install.sh
  blueprints/organizr/update.sh
  blueprints/plex/config.yml
  blueprints/plex/install.sh
  blueprints/plex/readme.md
  blueprints/plex/update.sh
  blueprints/radarr/install.sh
  blueprints/radarr/update.sh
  blueprints/sonarr/install.sh
  blueprints/sonarr/update.sh
  blueprints/tautulli/install.sh
  blueprints/tautulli/update.sh
  blueprints/transmission/install.sh
  blueprints/transmission/update.sh
  blueprints/unifi/config.yml
  blueprints/unifi/install.sh
  blueprints/unifi/readme.md
  blueprints/unifi/update.sh
  config.yml.example
  docs/CONTRIBUTING.md
  includes/global.sh
  includes/global.yml
  jailman.sh
Labels: Feature, enhancement

#142 Blueprint exit and includes refactor
  blueprints/bitwarden/install.sh
  blueprints/example/install.sh
  blueprints/influxdb/install.sh
  blueprints/jackett/install.sh
  blueprints/kms/install.sh
  blueprints/lidarr/install.sh
  blueprints/mariadb/install.sh
  blueprints/nextcloud/install.sh
  blueprints/organizr/install.sh
  blueprints/plex/install.sh
  blueprints/radarr/install.sh
  blueprints/sonarr/install.sh
  blueprints/tautulli/install.sh
  blueprints/transmission/install.sh
  blueprints/unifi/install.sh
  blueprints/unifi/update.sh
  docs/development/functions.md
  includes/global.sh
Labels: Feature, enhancement

#147 Refactor: Reinstall, CreateMount, Initblueprint
  blueprints/bitwarden/install.sh
  blueprints/example/config.yml
  blueprints/example/install.sh
  blueprints/mariadb/install.sh
  blueprints/nextcloud/install.sh
  docs/development/linked_configs.md
  includes/global.sh
Labels: enhancement

#153 Redo all the templates and remove the old once
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/general_improvement.md
  .github/PULL_REQUEST_TEMPLATE/new_blueprint.md
  docs/ISSUE_TEMPLATE.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#148 Add Bazarr
  blueprints/bazarr/config.yml
  blueprints/bazarr/includes/bazarr.rc
  blueprints/bazarr/install.sh
  blueprints/bazarr/readme.md
  blueprints/bazarr/update.sh
  config.yml.example
  docs/Readme.md
Labels: Feature

#154 Some small fixes
  config.yml.example
  includes/global.sh
Labels: bug

#144 Add Grafana
  blueprints/grafana/config.yml
  blueprints/grafana/includes/grafana.conf
  blueprints/grafana/includes/influxdb.yaml
  blueprints/grafana/install.sh
  blueprints/grafana/readme.md
  blueprints/grafana/update.sh
  config.yml.example
  docs/CODEOWNERS
Labels: enhancement

#146 Add Forked_Daapd blueprint
  blueprints/forked_daapd/build-daapd.sh
  blueprints/forked_daapd/build-ffmpeg.sh
  blueprints/forked_daapd/config.yml
  blueprints/forked_daapd/install.sh
  blueprints/forked_daapd/readme.md
  blueprints/forked_daapd/update.sh
  config.yml.example
  docs/CODEOWNERS
  includes/global.sh
Labels: Feature

#149 Add Traefik
  blueprints/traefik/config.yml
  blueprints/traefik/includes/dashboard.toml
  blueprints/traefik/includes/dashboard_wildcard.toml
  blueprints/traefik/includes/firewall.rules
  blueprints/traefik/includes/ssl.yml
  blueprints/traefik/includes/traefik.toml
  blueprints/traefik/install.sh
  blueprints/traefik/readme.md
  blueprints/traefik/update.sh
  config.yml.example
  docs/Readme.md
Labels: Feature, enhancement

#160 Fixup *arr versioning and updating
  blueprints/jackett/install.sh
  blueprints/jackett/update.sh
  blueprints/lidarr/install.sh
  blueprints/lidarr/update.sh
  blueprints/radarr/install.sh
  blueprints/radarr/update.sh
  blueprints/sonarr/update.sh
Labels: enhancement

#167 Create SECURITY.md
  SECURITY.md
Labels: documentation
